# -*- coding: utf-8 -*-
"""average.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYcccUQoJKHZeo5PjOSqkGTYukMLVggv
"""

import pandas as pd 
df = pd.read_csv("iris.csv")
avg = df["pw"].mean()
print(avg)
print(round(avg,2))