# -*- coding: utf-8 -*-
"""range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Ffpa8n5kQWAatCM6ZRZbkrtvhcMwdY-
"""

import pandas as pd
df = pd.read_csv("iris.csv")
def range():
    #calculate the range of pw#
    range_pw = df.pw.max()-df.pw.min()
    return (range_pw) 

rn = range()
print(rn)